### ISSUE TITLE
Put all contracts in a single repository

### ISSUE THREAD

**Issue by dcelasun** [elementary/contractor#29]
Is it possible to put all contracts from [the examples](https://github.com/elementary/contractor#examples) in a single repo? It would help with third party packaging [like for Arch Linux](https://github.com/alucryd/aur-alucryd/issues/73).

**Comment by danirabbit** [comment]
I'm going to close this as a "Design Conflict" since the goal is that applications supply their own contract files. elementary carries a minimal amount of patches for apps that are shipped by default and don't include their own contracts, but the contents of this report is essentially the same as asking if we can create a single repo for all of the .desktop files in the OS. It would just go against how the system is supposed to work.
